spring:
  application:
    name: meshgroup
  mesh-datasource:
    jdbcUrl: ${DB_JDBC_URL:jdbc:postgresql://localhost:5438/mesh?currentSchema=public&user=postgres&password=postgres}
    driverClassName: org.postgresql.Driver
    liquibase:
      enabled: true
      change-log: classpath:db/changelog/master.xml
    maximumPoolSize: ${MAXIMUM_POOL_SIZE:15}
springdoc:
  packagesToScan: ru.meshgroup.controller
  enabled: ${SPRINGDOC_ENABLED:true}
  api-docs:
    path: ${SWAGGER_DOCS_PATH:/swagger/v3/api-docs}
  swagger-ui:
    path: ${SWAGGER_UI_PATH:/swagger-ui}
app:
  task:
    scheduling:
      updateBalance: ${UPDATE_BALANCE:30000}
ignite:
  host-list: ${IGNITE_HOST_LIST:localhost,localhost}
  instance-name: ${IGNITE_INSTANCE_NAME:meshgroup}
  port: ${IGNITE_PORT:40000}
  end-port: ${IGNITE_END_PORT:40040}
  local-port: ${IGNITE_LOCAL_PORT:40050}
  client-port: ${IGNITE_CLIENT_PORT:40100}
  client-port-range: ${IGNITE_CLIENT_PORT:20}